### ISSUE TITLE
Syntax highlighting loses background highlighting of changed parts

### ISSUE THREAD

**Issue by mnn** [refined-bitbucket/refined-bitbucket#407]
Without syntax highlighting:

<img width="543" alt="2021-04-07_08-48" src="https://user-images.githubusercontent.com/1975567/113822887-48eb8480-977e-11eb-99ee-5626b5d0b493.png">

With syntax highlighting:

<img width="568" alt="2021-04-07_08-49" src="https://user-images.githubusercontent.com/1975567/113822947-5bfe5480-977e-11eb-9089-f8c1af4c598d.png">

It's a bit annoying. I am forced to frequently enable/disable the addon (usually per PR - for new code it's good to have syntax highlighting on, for changes it's better to see which parts were changed). It may not be that apparent from the simple example, but when you have a line of 120 characters and only one character changes, it takes longer to figure out what has changed with syntax highlighting on (so background diff is missing; if it's only few instances in PR then it's easy, but when you have changes in e.g. linter/formatting rules you get tons of such small changes).

**Comment by pastelsky** [comment]
This should fix it —
https://github.com/refined-bitbucket/refined-bitbucket/pull/410

**Comment by dereknheiley** [comment]
@pastelsky looks like the changes had to be disabled by a patch update, any ETA to re-enable? looks like it might have been an edge case or two that needed to be handled?

**Comment by mnn** [comment]
Unfortunately the problem is still present. These are fresh screenshots:

<img width="474" alt="2022-07-20_10-36" src="https://user-images.githubusercontent.com/1975567/179938819-5a937762-ae1b-4126-accf-4219207b4404.png">
<img width="467" alt="2022-07-20_10-37" src="https://user-images.githubusercontent.com/1975567/179938831-7c748cb5-a0aa-4d53-b22d-2a11538672b5.png">

Extension version: 3.26.1 (current on Chrome store)
Browser: Chromium 103.0.5060.114 (Official Build) Arch Linux (64-bit)

**Comment by DBX12** [comment]
Can confirm what @mnn says for Extension version 3.26.1 on `Firefox 91.12.0esr (64-bit)` on debian.
